language: python
python:
- 3.5
- 3.6
install:
- ".ci/travis-install.sh"
script:
- ".ci/travis-script.sh"
deploy:
  provider: pypi
  user: alexopryshko
  password:
    secure: S/5/Qubsp1oVC8rqm8p/8Yk+nOcMZlg7RpWZPoRvrKIqhLbQsvnuxF3im8PxIyTu3dc7zM0ROHv4HILQRzBV3sYLYTD/uLm8DHhNiilWDtfmZpiK+sMrg7J7b+sRM0A9bxkRZBKcL/KoWeVPmW3gK45TOJjT3aJzT2ogOpVPuVlt9aBNX3wH3EaWNVgaXNKo1D+EMxWrA+UbkwIdRLKfN38qkrDtFOpkleivk6lJ2Ka5KjwtNuJEO/n9CRGR1Jv9U/MC3MQ+AbSSn0UqXOPSHQa0/BnW2TkMPB/adxjgix0o7A5bsoOwO9hSK4Qx7+/ViifAEvBgvrgRpyunDYchQO+bAqjwikcm3yo2oSzFhjQYvI8O2GMCyJzIzx5t21nDpNAeNF/oDd4LT4v73GRqS4K6GexE0G01KPmpgMykhyDW0//evGBjFVA2AVDLkbur2s6AKD93dgZU/0pDz3RYbhyEifZowlsc5wKedILppmRTLWMNhm0qbqX2AjSPgRqT7P66ryg+qcZ+oTLbbPYtKG+7hs2vpVFAYr4qrxfLTxFEsneswaOkzQlXsVL3DDOBP6/wzjBuEh+ML8tMy5Y8IhXOK55Zsh1swCj0HpCC5iXl8UWnnxjKKgodKwZAwrNtfyh1fNo+Fg/jNZJL54tEBrNhVWFFqST4zc6FRRM9e6Q=
  on:
    tags: true
